steps:
  - name: golang:1.23
    id: Build
    entrypoint: /bin/bash
    args:
      - -c
      - |
        wget -nv -O gcs-cacher.tgz https://github.com/sethvargo/gcs-cacher/releases/download/v0.1.3/gcs-cacher_0.1.3_linux_amd64.tgz 
        tar -xvzf gcs-cacher.tgz
        ./gcs-cacher -bucket "tabuild" -restore "go-mod" -dir "/workspace/gomodcache"
        echo Building...
        go install ./internal/...
        go build -v -o /workspace/taf-server ./cmd/server
        ./gcs-cacher -bucket "tabuild" -cache "go-mod" -dir "/workspace/gomodcache"
    env:
      - 'CGO_ENABLED=0'
      - 'GOMODCACHE=/workspace/gomodcache'
  - name: golang:1.23
    id: Test
    entrypoint: /bin/bash
    args:
      - -c
      - |
        echo Testing...
        go test -coverprofile coverage.out -timeout 3m ./...
        go tool cover -html coverage.out -o /workspace/coverage-${SHORT_SHA}.html
        # ./gcs-cacher -bucket "tabuild" -cache "go-mod" -dir "/workspace/gomodcache"
    env:
      - 'CGO_ENABLED=0'
      - 'GOMODCACHE=/workspace/gomodcache'
  - name: gcr.io/cloud-builders/docker
    id: Package
    args:
      - build
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest
      - .
      - '-f'
      - Dockerfile
    env:
      - 'DOCKER_BUILDKIT=1'
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - '-a'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: europe-west2-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: taf-server
  _DEPLOY_REGION: europe-west2
  _TRIGGER_ID: 7c26f4f0-824e-452c-b82c-a9c86a33132d
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - taf-server
artifacts:
  objects:
    location: gs://tabuild
    paths:
      - /workspace/coverage-${SHORT_SHA}.html