steps:
  - name: golang:1.23
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go build ./internal/...
        go build -v -o /workspace/taf-server ./cmd/server
        go test -timeout 3m ./...
        echo "Step 1 data" > /workspace/step1.txt &&
        ls -l /workspace
    id: Test
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest
      - .
      - '-f'
      - Dockerfile
    env:
      - 'DOCKER_BUILDKIT=1'
    id: Package
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '-a'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: europe-west2-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: taf-server
  _DEPLOY_REGION: europe-west2
  _TRIGGER_ID: 7c26f4f0-824e-452c-b82c-a9c86a33132d
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - taf-server
